version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "laultimapieza-aws"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ptewcw0daof4"
s3_prefix = "laultimapieza-aws"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
