AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  laultimapieza-aws

  - Facebook CSV function

Globals:
  Function:
    Timeout: 3

Resources:
  FacebookCsvFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: facebook_csv/
      Handler: app.lambda_handler
      Runtime: ruby2.7
      Events:
        FacebookCsv:
          Type: Api
          Properties:
            Path: /facebook.csv
            Method: get

Outputs:
  FacebookCsvApi:
    Description: "API Gateway endpoint URL for Facebook Csv function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/facebook.csv"
  FacebookCsvFunction:
    Description: "Facebook Csv Lambda Function ARN"
    Value: !GetAtt FacebookCsvFunction.Arn
  FacebookCsvFunctionIamRole:
    Description: "Implicit IAM Role created for Facebook Csv function"
    Value: !GetAtt FacebookCsvFunctionRole.Arn
